### PR TITLE
12 create docker container only web app folder

### LINKED ISSUE #12: Create Docker Container only WebApp Folder

### PR DESCRIPTION
**Pull request by harikishantk**
Closes #12

### CODE REVIEW

**Comment by aryasoni98** [comment]
@harikishantk Update the README file too. Add command

**Comment by harikishantk** [comment]
Current update: Frozen the dependencies in the `requirements.txt`. While building the image, following packages:
- dlib
- cmake
- pyaudio
not able to install, due to some dependency error. Working on that part. If the dependency error resolved, the container can be run flawless.

**Review by aryasoni98 — CHANGES_REQUESTED** [review]
Screenshot 2021-12-21 at 3 49 38 PM
Screenshot 2021-12-21 at 3 49 42 PM

Resolve this error !

**Comment by harikishantk** [comment]
Resolved the errors.

**Comment by aryasoni98** [comment]
@harikishantk I'm still waiting for your update.

**Pull request merged**
